"""Runtime capabilities and execution boundaries for a request run."""

from __future__ import annotations

from pydantic import BaseModel, Field


class RuntimeContext(BaseModel):
    """Runtime capabilities and execution boundaries for a request run."""

    request_id: str = Field(
        min_length=1,
        description="Unique identifier for the current request run.",
    )
    user_id: str = Field(
        min_length=1,
        description="User ownership boundary for the current execution context.",
    )
    session_id: str = Field(
        min_length=1,
        description="Session boundary used to connect the current run to session continuity state.",
    )
    session_id_generated: bool = Field(
        default=False,
        description="Whether the session identifier was generated by the system rather than supplied by the caller.",
    )
    stage_history: list[str] = Field(
        default_factory=list,
        description="Ordered list of stage names already traversed in the current run.",
    )

    available_tools: list[str] = Field(
        default_factory=list,
        description="Tools currently available to the run for downstream stage input projection and execution.",
    )
    tool_registry_version: str | None = Field(
        default=None,
        description="Optional version identifier for the active tool registry.",
    )
    latency_budget_ms: int | None = Field(
        default=None,
        description="Optional latency budget in milliseconds for the current run.",
    )
    iteration_budget: int | None = Field(
        default=None,
        description="Optional upper bound on how many reasoning or research iterations the run should spend.",
    )
    scope_restrictions: list[str] = Field(
        default_factory=list,
        description="Scope restrictions that constrain what the current run is allowed to access or act on.",
    )
    environment_flags: list[str] = Field(
        default_factory=list,
        description="Runtime environment flags that affect execution behavior for the current run.",
    )
