"""Final response assembly skeleton."""

from app.domain.enums.task_type import TaskType
from app.domain.enums.workflow_pattern import WorkflowPattern
from app.domain.models import ActionItem, ExecutionContext, StructuredOutput
from app.services.output.contracts.response_assembler_protocol import ResponseAssemblerProtocol


class ResponseAssemblerService(ResponseAssemblerProtocol):
    """Assemble final structured output from execution context."""

    async def assemble(self, context: ExecutionContext) -> StructuredOutput:
        state = context.running_state
        runtime_context = context.runtime_context
        task_type = self._task_type_from_state(state.task_type)
        return StructuredOutput(
            trace_id=runtime_context.request_id,
            task_type=task_type,
            workflow_pattern=state.workflow_pattern or self._workflow_pattern_from_task_type(task_type),
            summary="Structured conclusion generated by skeleton flow.",
            recommendation=state.final_recommendation,
            action_items=[ActionItem(title=item) for item in state.action_items],
            citations=[],
            confidence=self._confidence_to_score(state.confidence),
            stage_history=runtime_context.stage_history,
            metadata={
                "session_id": runtime_context.session_id,
                "session_id_generated": runtime_context.session_id_generated,
            },
        )

    def _task_type_from_state(self, task_type: str | None) -> TaskType:
        if not task_type:
            return TaskType.TOPIC_EXPLORATION
        return TaskType(task_type)

    def _workflow_pattern_from_task_type(self, task_type: TaskType) -> WorkflowPattern:
        return {
            TaskType.TOPIC_EXPLORATION: WorkflowPattern.TOPIC_EXPLORATION,
            TaskType.COMPARISON: WorkflowPattern.COMPARISON,
            TaskType.RECOMMENDATION: WorkflowPattern.RECOMMENDATION,
            TaskType.ACTION_PLANNING: WorkflowPattern.ACTION_PLANNING,
            TaskType.TRACKING: WorkflowPattern.TRACKING,
        }[task_type]

    def _confidence_to_score(self, confidence: str | None) -> float | None:
        if confidence is None:
            return None
        return {
            "low": 0.2,
            "medium": 0.5,
            "high": 0.8,
        }.get(confidence.lower())
